# Generated by Django 3.2.3 on 2021-10-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyschool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
